tz:
  sigar-home: ./doc/sigar # 监控依赖目录
  html-source: ./admin-ui/ # html,css,js静态资源目录,必须以斜杠结尾
  storage:
    tmp-file-path: ./tmp-file #临时文件目录
    local-file-path: ./local-file #本地文件存放位置

# Tomcat
server:
  port: 8870
mybatis:
  config-location: classpath:mybatis-dev.xml
spring:
  devtools:
    add-properties: false
  datasource:
    druid:
      one:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tz_v1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
        username: root
        password: 123456
      two:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tz_qrtz?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
        username: root
        password: 123456
  redis:
    database: 0
    host: localhost
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
